server:
  port: 8082
  servlet:
    context-path:
  tomcat:
    uri-encoding: UTF-8
    basedir: ./tomcat
    max-threads: 2000
    min-spare-threads: 10
    accesslog:
      pattern: common
      enabled: true
      directory: logs
      prefix: jeeplus_access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
logging:
  level:
    root: INFO
    #    org.flowable: DEBUG
    com.jeeplus: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN
spring:
  servlet:
    multipart:
      maxFileSize:  1000MB
      maxRequestSize: 1000MB
  devtools:
    restart:
      enabled: false
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #  jpa:
  #    open-in-view: false
  datasource:
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        validation-query: select 'x' from dual
        SelectMethod: cursor
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
      p6spy: false # 默认false,线上必须关闭。开发阶段可以打开调试输出mybatis语句，但是有许多莫名其妙的bug，以及严重的性能问题，所以正式环境必须关闭。
      datasource:
        master:
          username: root
          password: Develope@25
          url: jdbc:mysql://59.195.128.25:3308/convenience-platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver
  #spring-ehcache的配置
  cache:
    type: redis # redis/ehcache， 在这里设置你使用的缓存框架，如果不想使用redis，请改成ehcache
  ehcache:
    config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379
    expireTime: 7200 #单位秒
  mvc.servlet.load-on-startup: 1
  jmx:
    enabled: false

#mybatis的配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
    - classpath*:com/jeeplus/modules/**/*Mapper.xml
    - classpath:/META-INF/admin-mybatis-mappings/*.xml
    - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  type-aliases-package: com.jeeplus.modules
  configuration-properties:
    prefix:
    boolValue: TRUE
    blobType: BLOB
#是否开启 swagger，生产环境请关闭
swagger:
  enable: true

mybatis-plus:
  mapper-locations: classpath*:/com/jeeplus/modules/**/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

retrofit:
  log:
    global-log-strategy: body

#============================#
#===== System settings ======#
#============================#

#产品信息设置
copyrightYear: 2019
version: springboot2.0
#演示模式: 不能操作和保存的模块： sys
demoMode: false
#上传文件绝对路径, 路径中不允许包含“userfiles”
userfiles:
  basedir:       # 文件上传路径，可以留空
  allowedType: file  # 允许上传的文件类型， all, file ,image, audio, video, office
  extensions:
    all: all       # 允许上传所有类型文件
    file: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip       # 只允许上传安全文件（linux系统非可执行）
    image: gif,jpg,jpeg,bmp,png     # 只允许上传图片
    audio: CD,OGG,MP3,ASF,WMA,WAV,MP3PRO,RM,REAL,APE,MODULE,MIDI,VQF    # 只允许上传音频
    video: AVI,WMV,RM,RMVB,MPEG1,MPEG2,MPEG4(MP4),3GP,ASF,SWF,VOB,DAT,MOV,M4V,FLV,F4V,MKV,MTS,TS     # 只允许上传视频
    office: txt,xls,xlsx,xlsm,xltx,xltm,xlsb,xlam,doc,docx,docm,dotx,dotm,ppt,pptx,pptm,ppsx,ppsm,potx,potm,ppam     # 只允许上传office文件
#JWT access token过期时间（access过期时间，并不是指需要重新登录的超时时间，而是指需要刷新重新获取access token的时间，超时登录的时间是3*EXPIRE_TIME，即refresh token的有效时时间)
jwt.accessToken.expireTime: 86400000 # 24小时，单位毫秒


#===============================#
#====== license 信息 ================#
#===============================#

# 产品授权
productId:
license:


#=======================================================================#
#===== plugin设置 =====#
#Plugin插件会读取该core和admin包下的基础类，如果修改了路径或者类名，请同步修改这里
#=======================================================================#
plugin:
  Page: com.jeeplus.core.persistence.Page
  User: com.jeeplus.modules.sys.entity.User
  Area: com.jeeplus.modules.sys.entity.Area
  Office: com.jeeplus.modules.sys.entity.Office
  UserUtils: com.jeeplus.modules.sys.utils.UserUtils

#=======================================================================#
#===== 项目设置 =====#
#自己项目里需要的一些配置项
#=======================================================================#
# 项目区划
project_region_code: 140000
project_region_name: 山西省

# 表单系统url
item_form_url: http://59.195.195.94:8807/form/

# 网盘
net_disk_url: http://59.195.195.94:8807/
net_disk_uid: 3335

# 事项系统
item_url: http://59.195.195.64:18088
item_client_id: IUMSBUW1N
item_secret: TOITGKV9BXCTEBWEFRCV
item_aes_password: inspur

# 统一身份认证Oauth2配置
oauth2:
  enabled: false
  api_url: http://59.195.195.94:8807/sso/
  base_url: http://59.195.195.94:8807/zwmh/
  client_id: R6SuZuilfQ
  client_secret: xHnVHWTpnca2lf0nA46S
